# Generated by Django 5.0.1 on 2024-01-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='typ',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
